name: CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  Component-E2E-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        id: Checkout
        uses: actions/checkout@v3
        with:
        fetch-depth: 0

      - name: Install dependencies
        id: install-dependencies
        run: npm install

      - name: Build Typescript
        id: build-typescript
        run: npm run build

      - name: Run tests
        id: run-tests
        run: npm run test
