name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          scopes: |
            ui
            core
            main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
